= Smals Pseudonymisation Helper
:authors: Laurent Lamouline and Mieke Nijs
:version: 0.1
:lang: en
:icons: font
:toc:
:toc-placement!:

:links-ehealth-doc: https://portal.api.ehealth.fgov.be/api-details?apiId=eb8015c0-693b-4c4f-bab9-f671d35ddc15&managerId=1&Itemid=171&catalogModuleId=120[eHealth Pseudonymisation service]

toc::[]

== Introduction
The Pseudonymization Helper is designed to pseudonymize sensitive data while also providing functionalities to identify/retrieve original values. This mechanism is essential for ensuring data privacy and security in applications that needs to handle personal or sensitive information.

== Features

* *pseudonymize :* Transform a clear text representation of sensitive data into its pseudonymized format.
* *pseudonymizeMultiple :* Transform multiple clear text representations of sensitive data into their pseudonymized format.
* *identify :* Retrieve the original clear text value based on its pseudonymized representation.
* *identifyMultiple :* Retrieve the original clear text values based on an array of pseudonymized data.

== Installation
To install the Pseudonymization Helper, use the following command:
----
npm install @smals-belgium-shared/pseudo-helper
----
== Usage

=== Creating a custom pseudonymisation client
First, implement the interface to call the eHealth Pseudonymization service. Create a custom class that extends PseudonymisationClient and overrides the predefined methods. The pseudonymisationClient is mandatory in all use cases.

Sample code to create a Custom Pseudonymisation Client
[source,javascript]
----
import {PseudonymisationClient} from "@smals-belgium-shared/pseudo-helper"

export class CustomPseudonymisationClient extends PseudonymisationClient {

  // Your pseudo api url
  private readonly pseudoApiUrl = 'https://${api-host-and-port}pseudo/v1/domains/';

  // built-in service used for making HTTP requests to backend servers
   constructor(private http: HttpClient (or AxiosInstance ...)) {
  }

  // Override the getDomain method
  getDomain(domainKey: string): Promise<string> {
     const request$ = this.http.get(this.pseudoApiUrl + domainKey);

    return lastValueFrom(request$);
  }

  // Override the identify method
  identify(domainKey: string, payload: string): Promise<string> {
   const request$ = this.http.post(this.pseudoApiUrl + domainKey + '/identify', payload).pipe(map(response => JSON.stringify(response)));

    return lastValueFrom(request$);
  }

  // Override the identifyMultiple method
  identifyMultiple(domainKey: string, payload: string): Promise<string> {
     const request$ = this.http.post(this.pseudoApiUrl + domainKey + '/identifyMultiple', payload).pipe(map(response => JSON.stringify(response)));

     return lastValueFrom(request$);
  }

  // Override the pseudonymize method
  pseudonymize(domainKey: string, payload: string): Promise<string> {
    const request$ = this.http.post(this.pseudoApiUrl + domainKey + '/pseudonymize', payload).pipe(map(response => JSON.stringify(response)))

    return lastValueFrom(request$)
  }

  // Override the pseudonymizeMultiple method
  pseudonymizeMultiple(domainKey: string, payload: string): Promise<string> {
    const request$ = this.http.post(this.pseudoApiUrl + domainKey + '/pseudonymizeMultiple', payload).pipe(map(response => JSON.stringify(response)));

    return lastValueFrom(request$);
  }
}
----

=== Creating a custom Pseudonymisation Helper
Next, create a custom PseudonymisationHelper were you instantiate a new object of the PseudonymisationHelper class, passing the custom client as an argument to its constructor.

Sample code to create a Custom Pseudonymisation Client
[source,javascript]
----
import { PseudonymisationHelper } from '@smals-belgium-shared/pseudo-helper';
import { CustomPseudonymisationClient} from "../client/customPseudonymisation.client";

export function PseudonymisationHelperFactory(
  client: CustomPseudonymisationClient
) {
  return new PseudonymisationHelper(client);
}
----

=== Inject the PseudonymisationHelper
Then register the PseudonymisationHelper that uses PseudoHelperFactory to create instances of that service.

Sample code in your Angular provider configuration
[source,javascript]
----
import {PseudonymisationHelper} from "@smals-belgium-shared/pseudo-helper/dist";
import { CustomPseudonymisationClient} from "../client/customPseudonymisation.client";
import {PseudonymisationHelperFactory} from "../factories/PseudonymisationHelper.factory";

...
  providers: [
    {
      provide: PseudonymisationHelper,
      userFactory: PseudonymisationHelperFactory,
      deps: [CustomPseudonymisationClient]
    }
...
----

=== Creating the Pseudo Service
Finally, create a custom service where you import the necessary module :
[source,javascript]
----
import {PseudonymisationHelper} from '@smals-belgium-shared/pseudo-helper';

@Injectable({providedIn: 'root'})
export class PseudoService {
  ...
}
----

==== Creating the PleudonymisationHelper and the domain
Create a new Pseudonymisation Domain, which is essentially a set of factories allowing you to create and manipulate different objects for applying pseudonymisation operations.

===== Sample code to create the domain
[source,javascript]
----
export class PseudoService {
  private pseudonymisationDomain: Domain;

  constructor(
    private configService: ConfigurationService,
    private pseudomationHelper: PseudonymisationHelper,
  ) {
    this.pseudonymisationDomain = this.pseudomationHelper.createDomain(${domainKey}, Curve.p521, this.pseudoApiUrl, 8);
  }
}
----

*Explanation:*

* *PseudoHelper:* This is the core helper from the pseudonymization package. It provides utilities for pseudonymisation processes.
* *createDomain:* Creates a new domain which will be the entry point of pseudonymization process. You need to pass the following parameters:
** *domainKey:* The key identifying the domain.
** *crv:* The cryptographic curve to be used. At the moment, the default value is _Curve.p521_
** *audience:* The intended audience of the domain.
** *bufferSize:* The size of the buffer for cryptographic operations.

===== Use the Domain
Once the domain has been created, you can use it to pseudonymize or identify values. The pseudonymized value can then be passed into the Pseudonymisation Client.

==== Sample Code for *Pseudonymizing* a value:
[source,javascript]
----
async pseudonymize(value: string): Promise<string> {
    return await this.pseudonymisationDomain.valueFactory.fromString(value).pseudonymize().then((res: PseudonymInTransit | EHealthProblem) => {
      if (res instanceof EHealthProblem) {
        throw new Error(res.detail)
      }
      return res.asString()
    })
  }
----

*Explanation:*

* *valueFactory:* Returns the ValueFactory of this domain.
** *ValueFactory:* Allows to create Value for a Domain.
** *Value:* Wrapper around an elliptic curve point representing a value, that provides useful methods to manipulate it.
* *fromString(value):* Creates a Value from the given String. The string will be internally converted to an array of bytes using UTF-8 Charset.
** *value:* String to convert to Value
** *InvalidValueExeption:* Throws an InvalidValueException If the value cannot be converted to a Value (if the value is too long).
* *pseudonymize:* Convert this Value to its Pseudonym representation.
* *result:* A random PseudonymInTransit for this Value or an EHealthProblem.
** *PseudonymInTransit:* Wrapper around an elliptic curve point that provides useful methods to manipulate eHealth pseudonyms.
*** *asString():* Returns the standard String representation of this PseudonymInTransit.
It returns the Base64 URL representation of the uncompressed SEC1 representation of the point followed by : and by the String representation of the TransitInfo (JWE compact). +
_Prefer this method instead of #asShortString() when the length of the String is not very important, because it avoids the recipient of this PseudonymInTransit to compute the Y coordinate of the point._
** *EHealthProblem:* The error object has following properties:

----
class EHealthProblem {
  type: string;
  title: string;
  status: string;
  detail: string;
  inResponseTo: string;
}
----

==== Sample Code for *Pseudonymizing* multiple values:
[source,javascript]
----
async pseudonymizeMultiple(values: string[]): Promise<string[]> {
    if (!this.configService.getEnvironmentVariable('enablePseudo')) {
      return values;
    }

    const asValues = values.map(value => this.pseudonymisationDomain.valueFactory.fromString(value));
    return await this.pseudonymisationDomain.valueFactory.multiple(asValues).pseudonymize().then((res: MultiplePseudonymInTransit | EHealthProblem) => {
      if (res instanceof EHealthProblem) {
        throw new Error(res.detail);
      }

      let pseudonymizedValuesAsString = [];
      for (let i = 0; i < res.lengthPoints(); i++) {
        let point = res.getPoint(i);
        if (!(point instanceof EHealthProblem)) {
          pseudonymizedValuesAsString.push(point.asString());
        } else {
          throw new Error(point.detail);
        }
      }

      return pseudonymizedValuesAsString;
    });
  }
----

*Explanation:*

* *valueFactory:* Returns the ValueFactory of this domain.
** *ValueFactory:* Allows to create Value for a Domain.
* *fromString(value):* Creates a Value from the given String. The string will be internally converted to an array of bytes using UTF-8 Charset.
** *value:* String to convert to Value
** *InvalidValueExeption:* Throws an InvalidValueException If the value cannot be converted to a Value (if the value is too long).
* *multiple(asValues):* Creates a MultipleValue object from the given Value array.
* *pseudonymize:* Convert the MultipleValue object to its MultiplePseudonymInTransit representation.
* *result:* A MultiplePseudonymInTransit corresponding to the input MultipleValue or an EHealthProblem.
** *MultiplePseudonymInTransit:* Wrapper around an elliptic curve point that provides useful methods to manipulate eHealth pseudonyms.
*** *getPoint():* Returns the computed PseudonymInTransit
**** *asString():* Returns the standard String representation of this PseudonymInTransit.
It returns the Base64 URL representation of the uncompressed SEC1 representation of the point followed by : and by the String representation of the TransitInfo (JWE compact). +
_Prefer this method instead of #asShortString() when the length of the String is not very important, because it avoids the recipient of this PseudonymInTransit to compute the Y coordinate of the point._
** *EHealthProblem:* The error object has following properties:

----
class EHealthProblem {
  type: string;
  title: string;
  status: string;
  detail: string;
  inResponseTo: string;
}
----

==== Sample Code to *Identify* multiple values :
[source,javascript]
----
async identify(value: string): Promise<string> {
    return await this.pseudonymisationDomain.pseudonymInTransitFactory.fromSec1AndTransitInfo(value).identify().then((res: Value | EHealthProblem) => {
      if (res instanceof EHealthProblem) {
        throw new Error(res.detail)
      }
      return res.asString()
    })
  }
----

*Explanation:*

* *pseudonymInTransitFactory:* Allows to create PseudonymInTransit for a Domain.
* *fromSec1AndTransitInfo(value):* Return A PseudonymInTransit created from the given  sec1AndTransitInfo.
** *value:* Base64 URL string representation (without padding) of the SEC1 encoded point (can be SEC1 compressed or uncompressed format),
followed by :, and by the string representation of the TransitInfo (JWE compact).
** *InvaliedValueExeption:* Throws an InvalidValueException if the format of the given sec1AndTransitInfo is invalid
* *identify:* Identify (de-pseudonymise) this PseudonymInTransit.
* *result:* The identified value or an EHealthProblem.
*** *asString():* Returns the value as a String. Convenient method that converts the bytes array (representing UTF-8 characters) to a String. Use it for text values.

==== Sample Code to *Identify* multiple values :
[source, javascript]
----
async identifyMultiple(pseudonymsInTransitAsString: string[]): Promise<string[]> {
    if (!this.configService.getEnvironmentVariable('enablePseudo')) {
      return pseudonymsInTransitAsString;
    }

    const pseudonymsInTransit = pseudonymsInTransitAsString.map(pseudonymInTransit => this.pseudonymisationDomain.pseudonymInTransitFactory.fromSec1AndTransitInfo(pseudonymInTransit));

    return await this.pseudonymisationDomain.pseudonymInTransitFactory.multiple(pseudonymsInTransit).identify().then((response: MultipleValue | EHealthProblem) => {
      if (response instanceof EHealthProblem) {
        throw new Error(response.detail);
      }

      let identifiedValuesAsString = [];
      for (let i = 0; i < response.lengthPoints(); i++) {
        let point = response.getPoint(i);
        if (!(point instanceof EHealthProblem)) {
          identifiedValuesAsString.push(point.asString());
        } else {
          throw new Error (point.detail);
        }
      }

      return identifiedValuesAsString;
    });
  }
----

*Explanation:*

* *pseudonymInTransitFactory:* Allows to create PseudonymInTransit for a Domain.
** *fromSec1AndTransitInfo(pseudonymInTransit):* Return A PseudonymInTransit created from the given  sec1AndTransitInfo.
*** *pseudonymInTransit:* Base64 URL string representation (without padding) of the SEC1 encoded point (can be SEC1 compressed or uncompressed format),
followed by : and by the string representation of the TransitInfo (JWE compact).
*** *InvaliedValueExeption:* Throws an InvalidValueException if the format of the given sec1AndTransitInfo is invalid
** *multiple(pseudonymsInTransit) :* convert the input array of pseudonyms in transit to their corresponding MultiplePseudonymInTransit representation
*** *MultiplePseudonymInTransit :*
**** *identify:* Identify (de-pseudonymise) this PseudonymInTransit.
**** *response:* The identified value array as a MultipleValue object or an EHealthProblem.
***** *MultipleValue:* The object representation of the identified values
***** *getPoint(${index}) :* Returns the identified Value
******* *asString():* Returns the value as a String. Convenient method that converts the bytes array (representing UTF-8 characters) to a String. Use it for text values.

== Explanation of the Domain
The Domain interface represents either your own or a foreign domain and defines getter methods to access the factory for creating and manipulating objects within that domain.

.Methods
[source,javascript]
----
  /**
   * Returns the {@link ValueFactory} of this domain.
   *
   * @return the {@link ValueFactory} of this domain
   */
  get valueFactory(): ValueFactory;

  /**
   * Returns the {@link PseudonymInTransitFactory} of this domain.
   *
   * @return the {@link PseudonymInTransitFactory} of this domain
   */
  get pseudonymInTransitFactory(): PseudonymInTransitFactory;

  /**
   * Returns the {@link PseudonymFactory} of this domain.
   *
   * @return the {@link PseudonymFactory} of this domain
   */
  get pseudonymFactory(): PseudonymFactory;

  /**
   * Returns the key of this domain.
   *
   * @return the key of this domain
   */
  get key(): string;
----

=== ValueFactory
The ValueFactory allows the creation of Value objects, such as a clear identifier to be pseudonymised.
It serves as the entry point to pseudonymise an identifier or a string, or as the output when a pseudonym is identified (de-pseudonymised).

.Methods
[source,javascript]
----
  /**
   * Returns the maximum size of the value (as bytes) that can be converted in a Point.
   * <p>
   * Please note that this is the maximum theoretical size. eHealth asks us not to pseudonymise data with a size exceeding 32 bytes.
   *
   * @return the maximum size of the value.
   */
  getMaxValueSize(): number

  /**
   * Creates a {@link Value} from the given array of bytes.
   *
   * @param value Raw value to convert to {@link Value}.
   * @return the {@link Value} for the given array of bytes
   * @throws InvalidValueException If the value cannot be converted to a {@link Value} (if the value is too long).
   */
  fromArray(value: Uint8Array): Value;

  /**
   * Creates a {@link Value} from the given String.
   * <p>
   * The string will be internally converted to an array of bytes using UTF-8 Charset.
   *
   * @param value String to convert to {@link Value}.
   * @return the {@link Value} for the given array of bytes
   * @throws InvalidValueException If the value cannot be converted to a Value (if the value is too long).
   */
  fromString(value: string): Value;

  /**
   * Create an empty {@link MultipleValue}.
   *
   * @return an empty {@link MultipleValue}.
   */
  multiple(): MultipleValue;

  /**
   * Create a {@link MultipleValue} containing the items of the given {@link Array}.
   * <p>
   * The items (references) of the given Array are copied to the returned {@link MultipleValue}.
   * Changes done on the collection will not be reflected on the returned {@link MultipleValue}.
   *
   * @param values {@link Array} of items to copy in the returned {@link MultipleValue}
   * @return a {@link MultipleValue} containing the items of the given {@link Array}
   */
  multiple(values: Array<Value>): MultipleValue;
----

=== PseudonymFactory
The PseudonymFactory is responsible for creating Pseudonym objects from points on the curve X and Y. If the point is invalid then InvalidPseudonymError is thrown.

.Methods
[source,javascript]
----
  /**
   * Create a {@link Pseudonym} from the given X coordinate.
   * <p>
   * The Y coordinate will be computed and one of the two possible values will be randomly chosen.
   *
   * @param x Base64 string representation of the X coordinate.
   * @return a {@link Pseudonym} having the given X coordinate.
   * @throws InvalidPseudonymError If the coordinates or the format are invalid.
   */
  fromX(x: string): Pseudonym;


  /**
   * @param x Base64 string representation of the X coordinate.
   * @param y Base64 string representation of the Y coordinate.
   * @return Pseudonym
   * @throws InvalidPseudonymError If the coordinates or the format are invalid.
   */

  fromXY(x: string, y: string): Pseudonym;


  /**
   * @param sec1 Base64 string representation of the Sec1 encoded point (can be Sec1 compressed format).
   * @return Pseudonym
   * @throws InvalidPseudonymError If the coordinates or the format are invalid.
   */
  fromSec1(sec1: string): Pseudonym;
----

=== PseudonymInTransitFactory
This factory allows to create PseudonymInTransit objects from a pseudonym and a transitInfo.

.Methods
[source,javascript]
----
  /**
   * @param pseudonym   the {@link Pseudonym} part of the {@link PseudonymInTransit}
   * @param transitInfo the {@link TransitInfo} part ot the {@link PseudonymInTransit}
   * @return A {@link PseudonymInTransit} created from the given {@link Pseudonym} and {@link TransitInfo}
   */
  from(pseudonym: Pseudonym, transitInfo: string): PseudonymInTransit;

  /**
   * Creates a {@link PseudonymInTransit} from the given coordinates, and transit info.
   *
   * @param x           Base64 string representation of the X coordinate.
   * @param y           Base64 string representation of the Y coordinate.
   * @param transitInfo the standard JWE compact representation (Base64 URL encoded String) of the transitInfo
   *                    which contains the scalar that will be used to unblind the given {@link Pseudonym}.
   * @return A {@link PseudonymInTransit} created from the given coordinates and transit info
   */
  fromXYAndTransitInfo(x: string, y: string, transitInfo: string): PseudonymInTransit;

  /**
   * @param sec1AndTransitInfo Base64 URL string representation (without padding) of the SEC1 encoded point (can be SEC1 compressed or uncompressed format),
   *                           followed by {@code :}, and by the string representation of the {@link TransitInfo} (JWE compact).
   * @return A {@link PseudonymInTransit} created from the given {@code sec1AndTransitInfo}
   * @throws InvalidPseudonymError if the format of the given {@code sec1AndTransitInfo} is invalid
   */
  fromSec1AndTransitInfo(sec1AndTransitInfo: string): PseudonymInTransit;

  /**
   * Create an empty {@link MultiplePseudonymInTransit}.
   *
   * @return an empty {@link MultiplePseudonymInTransit}.
   */
  multiple(): MultiplePseudonymInTransit;

  /**
   * Create a {@link MultiplePseudonymInTransit} containing the items of the given {@link Array}.
   * <p>
   * The items (references) of the given collection are copied to returned {@link MultiplePseudonymInTransit}.
   * Changes done on the collection will not be reflected on the returned {@link MultiplePseudonymInTransit}.
   *
   * @param pseudonymsInTransit {@link Array} of items to copy in the returned {@link MultiplePseudonymInTransit}
   * @return a {@link MultiplePseudonymInTransit} containing the items of the given {@link Array}
   */
  multiple(pseudonymsInTransit: Array<PseudonymInTransit>): MultiplePseudonymInTransit;
----

=== Value
A Value object represents a clear identifier, it is a wrapper around an elliptic curve point representing a value, that provides useful methods to manipulate it.

.Methods
[source,javascript]
----
  /**
   * Returns the value as a bytes array.
   * <p>
   * Use it for non-text values.
   *
   * @return the value as a bytes array
   */
  asBytes(): Uint8Array;

  /**
   * Returns the value as a String.
   * <p>
   * Convenient method that converts the bytes array (representing UTF-8 characters) to a String.
   * <p>
   * Use it for text values.
   *
   * @return the value as a String
   */
  asString(): string;

  /**
   * Returns this {@link Value} as a {@link Pseudonym}.
   * <p>
   * Should not be used in regular usage, but it can be convenient for testing/logging purpose.
   *
   * @return this {@link Value} as a {@link Pseudonym}.
   */
  asPseudonym(): Pseudonym;

  /**
   * Pseudonymize this {@link Value}.
   *
   * @return a random {@link PseudonymInTransit} for this {@link Value}.
   */
  pseudonymize(): Promise<PseudonymInTransit | EHealthProblem>;
----

=== Pseudonym
A Pseudonym object is a wrapper around an elliptic curve point that provides useful methods to manipulate eHealth pseudonyms.

.Methods
[source,javascript]
----
  /**
   * Returns binary representation of the X coordinate (as a byte array converted in a Base64 String using {@link Base64}).
   *
   * @return binary representation of the X coordinate (as a byte array converted in a Base64 String)
   */
  x(): string;

  /**
   * Returns binary representation of the Y coordinate (as a byte array converted in a Base64 String using {@link Base64}).
   *
   * @return binary representation of the Y coordinate (as a byte array converted in a Base64 String)
   */
  y(): string;

  /**
   * Uncompressed SEC1 representation of this point as a Base64 String (using the {@link Base64}).
   *
   * @return uncompressed SEC1 representation of this point as a Base64 String
   */
  sec1(): string;

  /**
   * Compressed SEC1 representation of this point as a Base64 String (using the {@link Base64}).
   *
   * @return compressed SEC1 representation of this point as a Base64 String
   */
  sec1Compressed(): string;
----

=== TransitInfo
Transit info containing encrypted information about the PseudonymInTransit. It contains the encrypted headers iat, exp and scalar which is the scalar to use to "decrypt" the PseudonymInTransit. It also contains public headers like iat and exp.

.Methods
[source,javascript]
----
  /**
   * Returns the JWE compact representation if this {@link TransitInfo}.
   *
   * @return the JWE compact representation if this {@link TransitInfo}.
   */
  asString(): string;

  /**
   * Returns the audience of this {@link TransitInfo}.
   * <p>
   * Basically, it is the URL of the {@link Domain}.
   *
   * @return the audience of this {@link TransitInfo}
   * @throws InvalidTransitInfoError if the transit info String cannot be parsed or is invalid
   */
  audience(): string;

  /**
   * Validate the header of this {@link TransitInfo}.
   *
   * @throws InvalidTransitInfoError if the transit info String cannot be parsed or is invalid
   */
  validateHeader(): void;

  /**
   * Retrieves the protected (unencrypted) headers as a Map containing key-value pairs.
   *
   * This map contains the headers {@code aud}, {@code kid}, {@code iat}, {@code exp}, {@code alg} and {@code enc}.
   *
   * @return {Map<string, string | number>} A Map where each key is a header name and each value is the corresponding header value.
   */
  get headers(): Map<string, string | number>;
----

=== PseudonymInTransit
A PseudonymInTransit object represents a pseudonymInTransit that contains a Pseudonym and TransitInfo objects.

.Methods
[source,javascript]
----
  /**
   * Returns the standard String representation of this {@link PseudonymInTransit}.
   * <p>
   * It returns the Base64 URL representation of the uncompressed SEC1 representation of the point
   * followed by `:` and by the String representation of the {@link TransitInfo} (JWE compact).
   * <p>
   * Prefer this method instead of {@link #asShortString()} when the length of the String is not very important,
   * because it avoids the recipient of this {@link PseudonymInTransit} to compute the Y coordinate of the point.
   *
   * @return the standard String representation of this {@link PseudonymInTransit}
   */
  asString(): string;

  /**
   * Returns the short String representation of this {@link PseudonymInTransit}.
   * <p>
   * It returns the Base64 URL representation of the compressed SEC1 representation of the point
   * followed by `:` and by the String representation of the {@link TransitInfo} (JWE compact).
   * <p>
   * Only use this method instead of {@link #asString()} when you need to shorten the String (to prevent a too long URL for example).
   * The drawback is that the recipient of this {@link PseudonymInTransit} will have to compute the Y coordinate of the point.
   *
   * @return the standard String representation of this {@link PseudonymInTransit}
   */
  asShortString(): string;

  /**
   * Identify (de-pseudonymise) this {@link PseudonymInTransit}.
   *
   * @return the identified value.
   */
  identify(): Promise<Value | EHealthProblem> ;

  /**
   * Returns the {@link TransitInfo}.
   *
   * @return the {@link TransitInfo}
   */
  get transitInfo(): TransitInfo;
----

== Cleartext values exceeding 32 bytes
To come...

== Cache
To come...

== References

* {links-ehealth-doc} documentation
* https://www.smalsresearch.be/basisprincipes-voor-een-moderne-pseudonimiseringsdienst/[Introductie tot de nieuwe eHealth pseudonimiseringsdienst] /
https://www.smalsresearch.be/basisprincipes-voor-een-moderne-pseudonimiseringsdienst-2/[Introduction au nouveau service de pseudonymisation eHealth]
* https://www.smalsresearch.be/download/presentations/20240606_webinar_pseudonimisatie_PRINT.pdf[Privacy in Practice Smart Pseudonymisation]
